matrix:
  include:

  - language: java
    jdk: oraclejdk12
    before_script: cd java
    addons:
      apt:
        packages:
        - ant
                   
  - language: cpp
    before_script: cd cpp
    script: find . -type f -iname *.cpp -execdir g++-9 -std=c++2a {} \;
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-9
